name: 'Deploy macOS VM with GUI (VNC) - Final Fix'

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Create New User and Enable VNC
        env:
          # This uses the SSH_PASSWORD secret from your repository settings
          VNC_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Create a new user named 'vncuser' to avoid permissions issues
          echo "Creating a new user 'vncuser'..."
          sudo dscl . -create /Users/vncuser
          sudo dscl . -create /Users/vncuser UserShell /bin/bash
          sudo dscl . -create /Users/vncuser RealName "VNC User"
          sudo dscl . -create /Users/vncuser UniqueID 1001
          sudo dscl . -create /Users/vncuser PrimaryGroupID 80
          sudo dscl . -create /Users/vncuser NFSHomeDirectory /Users/vncuser
          
          # Set the password for the new 'vncuser'
          echo "Setting password for 'vncuser'..."
          sudo dscl . -passwd /Users/vncuser "$VNC_PASSWORD"
          
          # Add the new user to the admin group
          echo "Adding 'vncuser' to the admin group..."
          sudo dscl . -append /Groups/admin GroupMembership vncuser
          
          # --- THE CRITICAL FIX IS HERE ---
          # Enable Legacy VNC mode for compatibility with RealVNC and other clients
          echo "Enabling Legacy VNC mode..."
          sudo defaults write /Library/Preferences/com.apple.RemoteManagement.plist VNCLegacyConnectionsEnabled -bool YES
          
          # Enable and configure Apple Remote Desktop (Screen Sharing/VNC)
          echo "Enabling VNC service for 'vncuser'..."
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users vncuser -privs -all -restart -agent -menu

      - name: Install and Run ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          echo "Installing and running ngrok..."
          brew install --cask ngrok
          ngrok authtoken $NGROK_TOKEN
          ngrok tcp 5900 &

      - name: Display Connection Info and Keep Alive
        run: |
          echo "VM is getting ready. Please wait a minute for ngrok to provide the VNC address."
          sleep 10
          
          # Fetch and display the public VNC address from the ngrok API
          VNC_URL=$(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' | sed 's/tcp:\/\///')
          
          echo "--------------------------------------------------------------------"
          echo "✅ VNC (GUI) ADDRESS: $VNC_URL"
          echo "   USER: vncuser"
          echo "   PASSWORD: [The password you set in SSH_PASSWORD secret]"
          echo "--------------------------------------------------------------------"
          
          # Keep the job running for 6 hours
          echo "VM will stay alive for 6 hours."
          sleep 21600
